# Generated by Django 5.0.7 on 2024-07-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='images/desktop wallpaper.jpg', null=True, upload_to='images'),
        ),
    ]
