# Generated by Django 5.0.7 on 2024-07-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image_1',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image_2',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image_3',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images'),
        ),
    ]
