# Generated by Django 5.0.7 on 2024-07-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_project_featured_image_1_project_featured_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='exp_f1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='exp_f2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='exp_f3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
